### ISSUE TITLE
etert er  dfg dfg

### ISSUE THREAD

**Issue by licinioamendes** [licinioamendes/testone#1]
dfgd gdfd fgf gd @tiago #1

- [ ]

**Comment by licinioamendes** [comment]
Nada a fazer

**Comment by TiagoLopes92** [comment]
Lorem Ipsum is simply dummy text of the printing and typesetting industry

**Comment by licinioamendes** [comment]
Que achas disto @TiagoLopes92?

**Comment by TiagoLopes92** [comment]
É pá para discussão é porreiro @licinioamendes

**Comment by licinioamendes** [comment]
Pois, e depois é possível estas ligações todas. Isto é um mini Jira, masi do que suficiente para o que queremos.

- [ ] Outra coisa
- [ ] Olá
- [ x] Olá

**Comment by TiagoLopes92** [comment]
Nice

**Comment by TiagoLopes92** [comment]
Parece ser simples, dá para colaborar

**Comment by licinioamendes** [comment]
[testone-0.1-beta1.zip](https://github.com/licinioamendes/testone/files/974661/testone-0.1-beta1.zip)

**Comment by licinioamendes** [comment]
Yah e ainda tens a cena das releases, pullrequests, wiki e projectos

**Comment by licinioamendes** [comment]
ah e milestones
